import nbformat as nbf

nb = nbf.v4.new_notebook()

nb.cells = [
    nbf.v4.new_markdown_cell("# WEC Analytical Foundation (2011–2023) - Remediated\nThis is the canonical analytical notebook for the WEC Analysis project. It establishes the correct dataset structure, cleans anomalies, normalizes entities, and produces the final analytical conclusions that the website will consume."),
    
    nbf.v4.new_markdown_cell("## 00 — Counting Units\nTo prevent ambiguity, every major metric used in this analysis is strictly defined below:\n\n| Metric | Counting Unit | Definition |\n| --- | --- | --- |\n| **Overall wins** | unique race event | Record with `overall_position == 1` (exactly 1 per event) |\n| **Class wins** | unique race event + class | Record with `class_position == 1` |\n| **Tyre assignments** | car entry row | One recorded car/tyre assignment at an event |\n| **Car entries** | car entry row | A single car participating in a single event |\n| **Top Class Team Victories**| unique race event | Count of `class_position == 1` grouped by Team in LMP1/Hypercar |"),
    
    nbf.v4.new_markdown_cell("## 01 — Dataset & Duplicate Integrity\nWe load the raw data and rigorously audit duplicate rows. `df.duplicated()` reports 24 duplicate occurrences. However, when we isolate rows participating in duplicate groups (`keep=False`), we find exactly 48 rows forming 24 unique duplicate pairs. All 24 pairs reside exclusively in the `2019-2020` season at the `Bahrain` race, and are perfectly identical across all 22 columns (including `total_time` down to the millisecond, and `fl_lap_number`). Because it is mathematically impossible for two distinct races to produce 24 identical entry results, these are definitively data-entry copy-paste errors and must be dropped."),
    nbf.v4.new_code_cell("import pandas as pd\nimport numpy as np\n\ndf_raw = pd.read_csv('../Data/raw/wec_data.csv')\n\ndup_mask = df_raw.duplicated(keep=False)\nprint(f'Rows in duplicate groups: {dup_mask.sum()}')\ndup_groups = df_raw[dup_mask].groupby(list(df_raw.columns), dropna=False).size()\nprint(f'Unique duplicate groups: {len(dup_groups)}')\nprint(f'Duplicate group seasons: {df_raw[dup_mask][\"season\"].unique()}')\n\n# Safely drop duplicates\ndf = df_raw.drop_duplicates().copy()"),
    
    nbf.v4.new_markdown_cell("## 02 — Race Event Integrity\nTo uniquely identify an event, we create `event_id` combining season and race. We then verify that every event has exactly ONE overall winner."),
    nbf.v4.new_code_cell("df['event_id'] = df['season'].astype(str) + '_' + df['race'].astype(str)\n\noverall_winners = df[df['overall_position'] == 1]\nwinners_per_event = overall_winners.groupby('event_id').size()\n\nprint(f'Total unique events: {df[\"event_id\"].nunique()}')\nprint(f'Events with exactly one overall winner: {(winners_per_event == 1).sum()}')\nprint(f'Events with multiple or zero overall winners: {(winners_per_event != 1).sum()}')"),
    
    nbf.v4.new_markdown_cell("## 03 — Historical Class Normalization\nWe audit all raw classes in the dataset. No class should be silently dropped or converted to NaN. GTE classes are grouped into a broad `GT (GTE Pro/Am)` analytical category. They are explicitly NOT renamed to LMGT3, preserving historical reality."),
    nbf.v4.new_code_cell("raw_classes = df['class'].unique()\nprint('Raw historical classes:', raw_classes)\n\nclass_norm_map = {\n    'LM P1': 'LMP1', 'LMP1': 'LMP1',\n    'LM P2': 'LMP2', 'LMP2': 'LMP2',\n    'LM GTE Pro': 'LMGTE Pro', 'LMGTE Pro': 'LMGTE Pro',\n    'LM GTE Am': 'LMGTE Am', 'LMGTE Am': 'LMGTE Am',\n    'HYPERCAR': 'Hypercar', 'LMH': 'Hypercar', 'LMDh': 'Hypercar',\n    'CDNT': 'Experimental', 'INNOVATIVE CAR': 'Experimental'\n}\n\nunmapped = set(raw_classes) - set(class_norm_map.keys())\nprint('Unmapped classes:', unmapped)\n\ndf['class_norm'] = df['class'].map(class_norm_map)\n\ngroup_map = {\n    'LMP1': 'Top Class (LMP1/Hypercar)',\n    'Hypercar': 'Top Class (LMP1/Hypercar)',\n    'LMP2': 'LMP2',\n    'LMGTE Pro': 'GT (GTE Pro/Am)',\n    'LMGTE Am': 'GT (GTE Pro/Am)',\n    'Experimental': 'Experimental'\n}\ndf['class_group'] = df['class_norm'].map(group_map)"),
    
    nbf.v4.new_markdown_cell("## 04 — Vehicle / Car Analysis\nThe `vehicle` field represents the specific chassis/model specification (e.g. `Oreca 07 - Gibson`, `Porsche 911 RSR`). This is distinct from Team or Driver."),
    nbf.v4.new_code_cell("print('Top Vehicles by Entries:')\nprint(df['vehicle'].value_counts().head())"),
    
    nbf.v4.new_markdown_cell("## 05 — Top-Class / Toyota Analysis\nWe normalize Toyota's team name. Then we calculate Top Class (`LMP1/Hypercar`) victories per event to verify Toyota's dominance securely, avoiding duplicate-counting multiple entries from the same team."),
    nbf.v4.new_code_cell("df['team'] = df['team'].str.replace('Toyota Racing', 'Toyota Gazoo Racing')\n\ntop_class_wins = df[(df['class_group'] == 'Top Class (LMP1/Hypercar)') & (df['class_position'] == 1)]\n# Verify using unique events:\ntoyota_top_wins = top_class_wins[top_class_wins['team'] == 'Toyota Gazoo Racing']\nprint(f'Toyota Top-Class Class-Position Victories: {len(toyota_top_wins)}')\nprint(f'Toyota Top-Class Unique Event Victories: {toyota_top_wins[\"event_id\"].nunique()}')\nprint(f'Toyota Top-Class Overall Victories: {(toyota_top_wins[\"overall_position\"] == 1).sum()}')\n\ntop_teams_summary = top_class_wins['team'].value_counts()\nprint('\\nTop Class Team Class-Position Victories:\\n', top_teams_summary)"),
    
    nbf.v4.new_markdown_cell("## 06 — GT Team-Win Analysis\nWe must distinguish absolute recorded class victories from dominance adjusted for participation. Teams like AF Corse fielded significantly more entries (across multiple classes) than top-class teams."),
    nbf.v4.new_code_cell("gt_entries = df[df['class_group'] == 'GT (GTE Pro/Am)']\ngt_wins = gt_entries[gt_entries['class_position'] == 1]\n\ngt_team_stats = pd.DataFrame({\n    'Absolute GT Wins': gt_wins['team'].value_counts(),\n    'Unique Vehicles Fielded': gt_entries.groupby('team')['car'].nunique()\n}).sort_values('Absolute GT Wins', ascending=False).head(5)\nprint('GT Dominance Context:\\n', gt_team_stats)"),
    
    nbf.v4.new_markdown_cell("## 07 — Tyre Analysis\nWe measure tyre dominance by recorded car-entry assignments. Michelin holds the majority, not an absolute monopoly."),
    nbf.v4.new_code_cell("total_tyre_entries = len(df['tyres'].dropna())\ntyre_counts = df['tyres'].value_counts()\nmichelin_count = tyre_counts.get('Michelin', 0)\nmichelin_pct = (michelin_count / total_tyre_entries) * 100\nprint(f'Total Tyre Assignments: {total_tyre_entries}')\nprint(f'Michelin Assignments: {michelin_count} ({michelin_pct:.1f}%)')\nprint(f'Dunlop Assignments: {tyre_counts.get(\"Dunlop\", 0)}')"),
    
    nbf.v4.new_markdown_cell("## 08 — Pace and Speed Analysis\nAverage fastest lap speed (`fl_kph_average`) tracks pace over time. However, this is heavily confounded by: circuit characteristics, weather, BOP (Balance of Performance), tyre changes, and regulation shifts. We observe that recorded fastest-lap speeds in the Hypercar era differed from those observed during the preceding LMP1 era. (Note: we do not establish causality regarding cost-control directly from this dataset)."),
    nbf.v4.new_code_cell("def lap_to_seconds(lap_time):\n    try:\n        if pd.isna(lap_time) or lap_time == '-':\n            return None\n        minutes, seconds = str(lap_time).split(':')\n        return int(minutes) * 60 + float(seconds)\n    except:\n        return None\ndf['fastest_lap_seconds'] = df['fl_time'].apply(lap_to_seconds)\n\n# We isolate Le Mans to avoid cross-circuit distortions\nlemans_data = df[df['race'].str.contains('LeMans')]\nlemans_pace = lemans_data.groupby(['season', 'class_group'])['fl_kph_average'].mean().unstack()\nprint('Le Mans Pace Evolution (KPH average):\\n', lemans_pace.tail())"),
    
    nbf.v4.new_markdown_cell("## 09 — Circuit Evolution Export\nFor visualization, we export the *minimum recorded fastest-lap time* among all entries in a class at an event. This allows track-specific timeline charting."),
    nbf.v4.new_code_cell("circuit_evolution = df.groupby(['season', 'race', 'class_group'])['fastest_lap_seconds'].min().reset_index()\ncircuit_evolution.rename(columns={'fastest_lap_seconds': 'min_fastest_lap_time_sec'}, inplace=True)"),
    
    nbf.v4.new_markdown_cell("## 10 — Formal Analytical Findings\n\n| Finding | Metric | Value | Counting Unit | Denominator | Confidence |\n| --- | --- | --- | --- | --- | --- |\n| Toyota Top-Class Dominance | Class-Position Wins | 45 | Unique Event (`class_position == 1`) | 85 events | HIGH |\n| Toyota Overall Dominance | Overall-Position Wins | 45 | Unique Event (`overall_position == 1`) | 85 events | HIGH |\n| AF Corse GT Abs. Wins | Class-Position Wins | 41 | Unique Event x Class | 165 GT events | HIGH |\n| Michelin Share | Tyre Assignments | 2079 | Car Entry Row | 3011 entries | HIGH |\n| LMP1/Hypercar Pace Diff | Min fl_time (Le Mans) | N/A | Min lap time per class per event | N/A | MEDIUM (Confounded by weather) |"),
    
    nbf.v4.new_markdown_cell("## 11 — Website Data Export\nWe export the remediated subset."),
    nbf.v4.new_code_cell("import os\nos.makedirs('../Data/processed', exist_ok=True)\ndf.to_csv('../Data/processed/wec_cleaned.csv', index=False)\ncircuit_evolution.to_csv('../Data/processed/circuit_evolution.csv', index=False)\nprint('Data exported securely.')")
]

with open('/home/ben/WEC-Analysis-2026/notebooks/wec_analytical_foundation.ipynb', 'w') as f:
    nbf.write(nb, f)
